name: CI & Deploy (Progressive Metrics)

on:
  push:
    branches: ["main", "feature/**", "fix/**"]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Syntax check
        run: python -m compileall -q src
      - name: Run tests (stdlib unittest)
        run: python -m unittest discover -s tests -p "test_*.py" -v

  deploy:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build site from CSV (dynamic metrics)
        run: python tools/build_site.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - name: Deploy to Pages
        id: deploy
        uses: actions/deploy-pages@v4
